name: BokujoDashCowcome
options:
  bundleIdPrefix: com.opekku2001
configs:
  Debug: debug
  Release: release
settings:
  INFOPLIST_FILE: Info.plist
  IPHONEOS_DEPLOYMENT_TARGET: "16.0"
  SWIFT_VERSION: "5.8"
targets:
  BokujoDashCowcome:
    type: application
    platform: iOS
    deploymentTarget: "16.0"
    sources: [Sources]
    settings:
      PRODUCT_BUNDLE_IDENTIFIER: com.opekku2001.bokujoDashCowcome
