name: iOS Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: macos-latest
    steps:
      # コード取得
      - uses: actions/checkout@v3

      # Xcodeのバージョン指定（必要なら修正）
      - name: Select Xcode
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: '16.0'

      # CocoaPodsやSwift Package Managerがあればここにステップを追加

      # ビルド
      - name: Build .xcarchive
        run: |
          xcodebuild clean \
            -project BokujoDashCowcome.xcodeproj \
            -scheme BokujoDashCowcome \
            -configuration Release \
            -archivePath ${{ github.workspace }}/build/BokujoDashCowcome.xcarchive archive

      # IPA書き出し用の設定ファイル（あとで作成します）
      - name: Export IPA
        run: |
          xcodebuild -exportArchive \
            -archivePath ${{ github.workspace }}/build/BokujoDashCowcome.xcarchive \
            -exportPath ${{ github.workspace }}/build/ipa \
            -exportOptionsPlist ExportOptions.plist

      # 成果物をアップロード
      #- name: Upload IPA Artifact
      #  uses: actions/upload-artifact@v2
      #  with:
      #    name: BokujoDashCowcome.ipa
      #    path: build/ipa/*.ipa
