name: iOS Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: macos-latest
    steps:
      # コード取得
      - uses: actions/checkout@v3

      # xcodegen をインストール
      - name: Install xcodegen
        run: |
          brew install xcodegen

      # project.yml から Xcode プロジェクトを自動生成
      - name: Generate Xcode project
        run: |
          xcodegen generate --spec project.yml

      # Xcodeのバージョン指定
      - name: Select Xcode
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: '16.2.0'

      # ビルド
      - name: Build .xcarchive
        run: |
          xcodebuild clean \
            -project BokujoDashCowcome.xcodeproj \
            -scheme BokujoDashCowcome \
            -configuration Release \
            -archivePath ${{ github.workspace }}/build/BokujoDashCowcome.xcarchive archive

      # IPA書き出し用の設定ファイル
     # - name: Export IPA
     #   run: |
     #     xcodebuild -exportArchive \
     #       -archivePath ${{ github.workspace }}/build/BokujoDashCowcome.xcarchive \
     #       -exportPath ${{ github.workspace }}/build/ipa \
     #       -exportOptionsPlist ExportOptions.plist

      # Upload ステップはコメントアウト済み
      # - name: Upload IPA Artifact
      #   uses: actions/upload-artifact@v2
      #   with:
      #     name: BokujoDashCowcome.ipa
      #     path: build/ipa/*.ipa
